name: my first workflow
on: push
jobs:
  javaSdks:
    runs-on: ubuntu-latest
    steps:
      - name: java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - run: java --version
  