name: my first workflow
on: push
jobs:
  javaSdks:
    runs-on: ubuntu-latest
    steps:
      - name: java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
      - run: java -version
      - name: java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - run: |
          echo ${{toJson(github)}}